### ISSUE TITLE
Redundant context in genesis document

### ISSUE THREAD

**Issue by stevenvegt** [bcgov/trustdidweb-py#2]
In the genesis document, the `@context` array includes the `https://w3id.org/security/multikey/v1` context which does not seems to be needed since currently only the `id` field is set.

https://github.com/bcgov/trustdidweb-py/blob/d730195c7c5afd1ac3536e72b69b62f094452390/did_tdw/provision.py#L109-L119

**Comment by andrewwhitehead** [comment]
Thanks, this is fixed now.
